### ISSUE TITLE
creating a table using the ruby api specifies the wrong geometry type in geometry_columns

### ISSUE THREAD

**Issue by tokumine** [CartoDB/cartodb-rb-client#6]
When we create a table using the ruby api, the column specified in geometry_columns view is GEOMETRY. This should be the type of the geometry we specify (eg POINT, MULTIPOLYGON, MULTILINESTRING).

**Comment by Ferdev** [comment]
Closing this issue, should be working now.

**Comment by tokumine** [comment]
Excellent!

On Fri, Mar 23, 2012 at 2:48 PM, Fernando Espinosa
reply@reply.github.com
wrote:
