### ISSUE TITLE
INSERT should use RETURNING rather than doing a full select

### ISSUE THREAD

**Issue by tokumine** [CartoDB/cartodb-rb-client#9]
also, using currval **cannot be relied on** when you have multiple workers all making simultaneous inserts.

Suggest using RETURNING id 

http://archives.postgresql.org/pgsql-general/2009-02/msg00020.php

**Comment by simaob** [comment]
The update_row seems to have the same behaviour, so might be worth to update accordingly. =) Cheers

**Comment by Ferdev** [comment]
Thanks for this issue, didn't know about the RETURNING command :) 

It's fixed, so now we're saving an extra select query, that, as Simon said, it wasn't safe.

**Comment by simaob** [comment]
Kudos from WCMC to you guys :)
